### ISSUE TITLE
MarkTextAsSpoken Issues

### ISSUE THREAD

**Issue by cgordon5025** [morganney/tts-react#38]
I am trying to get my text to be marked as spoken however even in the demo it doesn't always mark it. Could this be my device (Alienware x17 R2)?  In the demo, on this device only the EN-US voice works with MarkTextAsSpoken.
 Below is the code that I am using. I am using JS. 
```
     <TextToSpeech
                    markTextAsSpoken
                    rate={".9"}
                    lang="en-GB"
                    autoPlay>
                    <p>How old are you?</p>
                </TextToSpeech>
```

**Comment by morganney** [comment]
I would say yes, it is related to the combination of OS/Browser/Lang/Locale. What browser are you using? If you notice the [Languages](https://morganney.github.io/tts-react/?path=/story/tts-react--languages) story includes the text under the select:

> (Some voices may create skewed word boundaries for the given text.)

Also, if you check the first and second FAQ from the README, you will notice that they address potential issues with `markTextAsSpoken`, and that for some devices (particularly Android) it is impossible to mark the word boundaries due ot a lack of support from the OS. As an example, check out [this chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=521666#c7).

Finally, I've noticed that you've assigned the `rate` prop as a `string`, when the actual type is a `number`. Here is an example of the text being highlighted on macOS/Chrome with your sample code (`rate` switched to `number`):

![LWjTJ8Z9rc](https://user-images.githubusercontent.com/848178/222504739-d664c0c3-0ecf-4147-99b4-f03231352683.gif)

Unfortunately, your only real solution is to find a suitable `voice` for your given `spokenText`, on your supported platform(s).
