### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by alanhung317** [morganney/tts-react#40]
Thank you for creating this package!

I ran into this error whenever I refresh/re-render the webpage:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/59635681/226195416-312801c2-e8c2-42cd-aaea-e76e491b34f6.png">

The error leads to this:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/59635681/226195614-949a2e2a-b9a3-4aa1-b746-f7f7392a381e.png">

My code:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/59635681/226195432-3d2e6fcc-7748-46be-8ebe-8e64106160f2.png">

I'm using Next js & the latest tts-react.
<img width="138" alt="image" src="https://user-images.githubusercontent.com/59635681/226195684-758d8ad1-daf7-4978-a3e7-339dddf1ec3e.png">
<img width="182" alt="image" src="https://user-images.githubusercontent.com/59635681/226195696-d04e2fd4-6be9-452b-b310-9d13b85ba80d.png">

It works again when I hide/unhide my TextToSpeech code, but throws the same error when I refresh the page.

Thank you!

**Comment by morganney** [comment]
Thanks for pointing this issue out.

You are looking for a [CJS](https://nodejs.org/api/modules.html) build which is currently not available, but should be. I'll have to publish a new version of `tts-react` that includes a CommonJS build.

In the meantime, you can try using [transpileModules](https://nextjs.org/docs/advanced-features/compiler#module-transpilation) from Next.js. and add `tts-react`. Basically you need to convert the `import/export`'s from this package into `require/module.exports` during your app's build.

**Comment by alanhung317** [comment]
Ok! thank you so much!

**Comment by alanhung317** [comment]
Just fyi,

I followed the direction to implementing `tts-react` via Next.js' Module Transpilation.
<img width="321" alt="image" src="https://user-images.githubusercontent.com/59635681/226202227-904b273f-42a1-441f-ae46-b00a2937b90c.png">

It produced an error of "window is undefined"
<img width="559" alt="image" src="https://user-images.githubusercontent.com/59635681/226202073-17e2f818-f861-4662-bae2-0a7cd7af491a.png">

I then used `useEffect` and `useState` to implement the package. It works now. (perhaps there's a better way)
<img width="378" alt="image" src="https://user-images.githubusercontent.com/59635681/226201795-d53d5658-d7b7-43f0-8c7d-880c485f0066.png">

**Comment by morganney** [comment]
Since `tts-react` uses the browser's [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API), you need the standard `window` checks for Next.js before rendering `TextToSpeech` or calling `useTts`. It is not possible to render on the server since the necessary API is not implemented in Node as far as I know.

Your approach seems standard for Next.js apps. You could also load this package [dynamically](https://nextjs.org/docs/advanced-features/dynamic-import).

**Comment by alanhung317** [comment]
Ok, thank you!
