### ISSUE TITLE
How to combine with Microsoft Azure speech API?

### ISSUE THREAD

**Issue by 55Cancri** [morganney/tts-react#46]
The Microsoft AI voices are the best in the industry. They are natural sounding and have better cadence than the native WebSpeech Api. However, I am not able to highlight the currently playing word with `microsoft-cognitiveservices-speech-sdk`. How can I merge `microsoft-cognitiveservices-speech-sdk` with your package?

**Comment by morganney** [comment]
Thanks for your question. This package is meant to be used on the web, in a browser, backed by **native** browser API's. The `microsoft-cognitiveservices-speech-sdk`, clearly does not fall into this category.

Can you provide some more detail on how exactly you would want to _merge_ this package with an external service and custom API? From the outset, I can tell it would require a chunk of work to adapt the custom API from MS to the native Browser Web Speech API. There is also the security issue of dealing with [tokens/keys that you probably don't want to expose to the browser](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser/#token-exchange-process), so a backend would be required (this is most likely a deal breaker for integration with this package).

Check out the Web SDK example: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser

**Comment by naeem-hassan** [comment]
> The Microsoft AI voices are the best in the industry. They are natural sounding and have better cadence than the native WebSpeech Api. However, I am not able to highlight the currently playing word with `microsoft-cognitiveservices-speech-sdk`. How can I merge `microsoft-cognitiveservices-speech-sdk` with your package?

@morganney 

I'm also looking for this. I've a backend server where i get the voice from Microsoft-cognitiveservices-speech-sdk. Now, sav the speech file to the server upload it to S3 and get the link and send it back to the client. Now, what I want is that , as the audio plays , the word must be highlighted. I've seen the storybook but couldn't find it more informative as there was mentioned couple of things those were confusing. I've also been search for Aws Polly, but couldn't find anything informative as you've mentioned in the story book that we can use AWS Polly to get the audio data. Hope you got the point.

**Comment by morganney** [comment]
@naeem-hassan 
  If the backend using `microsoft-cognitiveservices-speech-sdk` can return data matching the [`TTSAudioData`](https://github.com/morganney/tts-react/blob/main/packages/tts-react/src/controller.ts#L26) interface then you should be able to use the `fetchAudioData` prop to get what you want. To highlight the word spoken the backend needs to return the `marks` in the same format used by [AWS Polly Speech Marks](https://docs.aws.amazon.com/polly/latest/dg/using-speechmarks.html). There is an [example story](https://morganney.github.io/tts-react/?path=/story/tts-react--amazon-polly), check the source code in the repo.

**Comment by naeem-hassan** [comment]
I don't think so microsoft-cognitiveservices-speech-sdk is returning the `Marks` or is there any API or parameter to get this? Is there any free API to get the marks, as the AWS Polly is pretty expensive for me right now?
