### ISSUE TITLE
How to config voice?

### ISSUE THREAD

**Issue by xclidongbo** [morganney/tts-react#55]
How to config voice?
any enum?

```
const CustomTTSComponent = ({ children, highlight = false }: CustomProps) => {
  const { ttsChildren, state, play, stop, pause } = useTts({
    children,
    markTextAsSpoken: highlight,
    lang: "zh-CN",
    autoPlay: true,
void: ?????
  });

  return (
    <div>
      <>
        <button disabled={state.isPlaying} onClick={play}>
          Play
        </button>
        <button disabled={!state.isPlaying} onClick={pause}>
          Pause
        </button>
        <button onClick={stop}>Stop</button>
      </>
      {ttsChildren}
    </div>
  );
};

```

**Comment by morganney** [comment]
The availability of any [`SpeechSynthesisUtterance.voice`](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/voice) is dependent upon the device being used, so it's not really practical to provide an enumerated list of variable data entitites, as it wouldn't be accurate in general.

This package could potentially provide a hook `useVoices()` to asynchronously load the `SpeechSynthesisVoice[]` list available on the device.  From there you could provide a dropdown or dynamically select one `voice` from the list to use, but it would not support static enumeration.

The [story for the hook](https://morganney.github.io/tts-react/?path=/story/tts-react--hook) source code provides an example of how to load the voices available on the device and then use them with a dropdown. You should be able to tailor that example to your specific needs. You should also consult the [`getVoices()` documentation](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/getVoices).

**Comment by morganney** [comment]
Forgot to mention you can provide a `lang` instead of `voice` using an enum: https://github.com/morganney/tts-react/blob/main/packages/tts-react/src/languageTags.ts

**Comment by xclidongbo** [comment]
3Q
