### ISSUE TITLE
Does not work after 255 characters

### ISSUE THREAD

**Issue by ritikbanger** [morganney/tts-react#63]
Steps to reproduce:

Pass 500 characters paragraph as children to tts.

**Comment by morganney** [comment]
Hi, thanks for filing the issue.

It would be helpful if you mentioned your browser and OS.  However, I'm betting your platform offers no local `SpeechSynthesisVoice`s. You can check by running `speechSynthesis.getVoices().filter(({ localService }) => localService)` in your browser console. If that returns an empty array then you only have network-based voices. These also do not fire `boundary` events: https://stackoverflow.com/questions/75177288/onboundary-event-doesnt-fire-in-chrome-on-ubuntu-20-04-and-above/77889844#77889844

I haven't seen this documented anywhere as a specification, but I think the network based voices have a character limit. Here is another post about this issue on SO: https://stackoverflow.com/questions/63996511/speech-synthesizer-on-chrome-only-play-the-first-200-characters

FWIW, I've confirmed that on platforms that have local voices (macOS/Windows/ChromeOS), this package works fine. In fact, the issue has nothing to do with this package at all, and you can replicate it by using the native `SpeechSynthesisUtterance` and passing your text to that and run it through `speechSynthesis.speak`. You can check out [this story](https://morganney.github.io/tts-react/?path=/story/tts-react--random-text) on a platform with local voices to see that it works properly.

Closing, as this package is working as expected and the limitation is imposed by the platforms.
